"""init

Revision ID: 0dcc17710f69
Revises: 
Create Date: 2022-09-24 13:25:09.564310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dcc17710f69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Languages',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=25), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('Users',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('TelegramID', sa.BIGINT(), nullable=True),
    sa.Column('LanguageID', sa.INTEGER(), nullable=False),
    sa.Column('RecoveryKey', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['LanguageID'], ['Languages.ID'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('RecoveryKey'),
    sa.UniqueConstraint('TelegramID')
    )
    op.create_table('Notes',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('OwnerID', sa.INTEGER(), nullable=False),
    sa.Column('Title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('Text', sa.VARCHAR(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['OwnerID'], ['Users.ID'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Notes')
    op.drop_table('Users')
    op.drop_table('Languages')
    # ### end Alembic commands ###
